Show error message dialog when failed to extract an archive file
jupyterlab-contrib/jupyter-archive pull request #101
Opened 2022-10-18 07:33 UTC by aidy1991

Ref #100 

This PR shows an error message dialog when extraction failed like below image.
![ScreenShot 2022-10-18 16 21 21](https://user-images.githubusercontent.com/4404574/196364280-a466130e-f2cf-42b1-a38d-d2b8889774e0.png)

For example, if I implement `raise web.HTTPError(400, "detailed error message")` on the notebook server side,
is there a good way to display this `detailed error message` in the dialog?
Since error response is returned in HTML, I could not find a good way to do it.

2022-10-18 14:20 UTC, aidy1991 commented on src/index.ts
> +      throw error;
Thank you for your suggestion. It needed a few modifications, but it worked very well.

2022-10-18 14:24 UTC, aidy1991 commented on jupyter_archive/handlers.py
> +class ExtractArchiveHandler(APIHandler):
To return json response, we need to use `APIHandler` instead of `JupyterHandler`.
Do you have any concern to use it?

2022-10-18 14:24 UTC, aidy1991 commented on src/index.ts
> +        throw new ServerConnection.ResponseError(response);
It seems current config of typescript does not support `finally()`.

```
error TS2550: Property 'finally' does not exist on type 'Promise<void>'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2018' or later.
```

2022-10-18 14:25 UTC, aidy1991 commented on src/index.ts
> +      throw error;
![ScreenShot 2022-10-18 23 19 21](https://user-images.githubusercontent.com/4404574/196458179-467f1657-85f0-4bec-b422-07ba84f15e8c.png)

2022-10-24 10:03 UTC, fcollonval requested changes
Thanks for the update @aidy1991

2022-10-24 10:38 UTC, aidy1991 commented on jupyter_archive/handlers.py
> +class ExtractArchiveHandler(APIHandler):
Thank you for your feedback.
It seems that `APIHandler.write_error()` is necessary and sufficient, so I ported the process as it was.
If it contains unnecessary processing or we need a simpler implementation, please let us know.

2022-10-24 13:09 UTC, fcollonval approved these changes
Thanks!

2022-10-24 13:09 UTC, merged

2022-10-24 22:57 UTC, aidy1991 commented
Thank you for your review and merge!

2022-10-25 06:53 UTC, fcollonval commented
Thank a lot to you for the various contributions