Fix filename decoding issue for zip files archived by macOS
jupyterlab-contrib/jupyter-archive pull request #75
Opened 2021-11-24 15:56 UTC by Wh1isper

this is how I fix https://github.com/jupyterlab-contrib/jupyter-archive/issues/74

2021-11-25 10:07 UTC, fcollonval requested changes
Thanks @Wh1isper 

I have a couple of suggestions. And could you update the workflow `.github/workflows/build.yml` on all OSes, so the tests will cover this use case.

2021-11-25 10:07 UTC, fcollonval commented on jupyter_archive/handlers.py
> +                    correct_filename = try_macos_decode(fn) or try_windows_chinese_decode(fn) or fn
Could you change this a bit to use a single function that has the following structure:

```py
def decode_filename(fn):
    try:
        encoded_filename = fn.encode('cp437')
        try:
            # MacOS encoding
            return encoded_filename.decode('utf-8')
        except UnicodeError:
            # Windows encoding
            return encoded_filename.decode('gbk')
    except UnicodeError:
        return fn
```

2021-11-25 10:07 UTC, fcollonval commented on jupyter_archive/handlers.py
> +                    extreact_path.rename(os.path.join(destination, correct_filename))
`destination` is a `Path`, so you can write:

```suggestion
                    extracted_path.rename(destination / correct_filename)
```

2021-11-25 10:07 UTC, fcollonval commented on jupyter_archive/handlers.py
> +                    extreact_path = pathlib.Path(f.extract(fn, path=destination))
Fix wording

```suggestion
                    extracted_path = pathlib.Path(f.extract(fn, path=destination))
```

2021-11-25 10:07 UTC, fcollonval commented on jupyter_archive/handlers.py
> +
```suggestion
```

2021-12-01 15:48 UTC, Wh1isper commented
well, I found this is not a good way to solve this problem
but anyone need this temporarily solution can refer my fork

2021-12-01 15:48 UTC, closed without merging